### ISSUE TITLE
Unwrapper fails if python file contains unknown imports

### ISSUE THREAD

**Issue by Mixaill** [extremecoders-re/pjunwrapper#1]
1. Create test.py
```
import BigWorld
print "test"
```

2. protect it with PjOrion

3. try to uwrap

4.
```
./pjunwrapper.py - test.pyc 
XXX lineno: 1, opcode: 234
XXX lineno: 1, opcode: 223
XXX lineno: 1, opcode: 165
Traceback (most recent call last):
  File "junwrapper.py", line 59, in <module>
    eval(co)
  File "test", line 1, in <pjorion_protected>
  File "test, line 1, in <pjorion_protected>
  File "test", line 1, in 
ImportError: No module named BigWorld
```

**Comment by adisadi** [comment]
i think one check is "type(BigWorld.player)==types.BuiltinFunctionType"
but there are others...

**Comment by FriedTM** [comment]
Any solution to this yet?

**Comment by neeeeecka** [comment]
https://github.com/jhakonen/wot-teamspeak-mod/releases/tag/ts-3.1-beta

Download this, go to futes/fakes/ Copy all files into pjUnwrapper folder
